Feat/place list pagina de busca
On-Maps/web pull request #18
Opened 2023-03-25 20:26 UTC by lorenzoMalutta

2023-03-26 15:47 UTC, Gabriellimmaa requested changes
Adicionei varios comentários neste PR
Principais pontos:
- A estilização tem q ficar no final do arquivo para não poluir a leitura
- O card e a lista tem q ser diferente do mapa pois nesta página você consegue carregar mais informações, então precisa reestrutura essa parte e pensar em algo diferente 
- CSS Module não vamos utilizar mais! Agora é só MUI
- Cuidado ao subir o PR pois existe varios arquivos vazios desnecessários

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/[...params].tsx
> +const PlaceId = () => {
Estamos usando o conceito de function então vamos evitar ao máximo utilizar o const como função. No caso deveria ser
export default function PlaceID ...

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/components/SelectCampus/styles/placeList.module.css
Arquivo vazio no projeto, tenta sempre fazer um review geral antes de subir o PR pra evitar esse tipo de poluição na estrutura

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/index.tsx
> +            ...flexCenterContent, gap: 2, alignItems: 'center', backgroundColor: '#fff', borderRadius: 2, boxShadow: 2, md: { flexDirection: 'row' }
Estilização coloca tudo na const style no final do arquivo. Quando coloca as estilizações assim fica muito poluida a tela

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/index.tsx
> +            display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', gap: 2, p: 4, fontSize: 20, fontWeight: 600, color: '#0000008A'
Estilização no styles no final do arquivo

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/index.tsx
> +                  ? `Pesquise por ${campus === 'cornelio' ? 'Cornélio Procópio' : campus === 'bandeirantes' ? 'Bandeirantes' : 'Jacarezinho'}` : 'Selecione um campus'
Isso aqui ficou ruim de ler, se bater o olho não sei ao certo oq está acontecendo. O ideal é fazer uma const ou uma function com essas condicionais ai vc consegue colocar o nome da function para entender oq está acontecendo.
``` 
const customPlaceholderInput = (campus: string) => {
    switch (campus) {
      case 'cornelio':
        return 'Pesquise por Cornélio Procópio'
      case 'bandeirantes':
        return 'Pesquise por Bandeirantes'
      case 'jacarezinho':
        return 'Pesquise por Jacarezinho'
      default:
        return 'Selecione um campus'
    }
  }

placeholder={customPlaceholderInput(campus ? campus : 'default')}

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/index.tsx
> +                height: 'auto',
Estilização fica tudo no final do arquivo

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/index.tsx
> +          width: 1, alignItems: 'center', display: 'flex', gap: 2, flexDirection: 'column', backgroundColor: '#fff', borderRadius: 2
Estilização final do arquivo

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/index.tsx
> +            sx: {
Isso aqui tambem da pra ficar no styles no final do arquivo

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/styles/list.module.css
Arquivo vazio

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/styles/place.module.css
Arquivo vazio

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/styles/PlaceCardSearch.module.css
Agora vamos usar MUI para tudo então o card e a listagem tem que usar o MUI. CSS Module não vamos utilizar mais!! só em um caso bem especifico caso ocorra

2023-03-26 15:47 UTC, Gabriellimmaa commented on src/pages/place/list/components/_PlaceCardSearch.component.tsx
O Card e a listagem tem q ser diferente da do Mapa pois aqui consegue carregar mais informações tanto na listagem quanto no card. Tem q reestruturar ambos e pensar em outra coisa.

2023-03-28 21:45 UTC, lorenzoMalutta commented on src/components/SelectCampus/styles/placeList.module.css
fixed

2023-03-28 21:46 UTC, lorenzoMalutta commented on src/pages/place/list/index.tsx
> +            ...flexCenterContent, gap: 2, alignItems: 'center', backgroundColor: '#fff', borderRadius: 2, boxShadow: 2, md: { flexDirection: 'row' }
fixed

2023-03-28 21:46 UTC, lorenzoMalutta commented on src/pages/place/list/index.tsx
> +            display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', gap: 2, p: 4, fontSize: 20, fontWeight: 600, color: '#0000008A'
fixed

2023-03-28 21:50 UTC, lorenzoMalutta commented on src/pages/place/list/index.tsx
> +                  ? `Pesquise por ${campus === 'cornelio' ? 'Cornélio Procópio' : campus === 'bandeirantes' ? 'Bandeirantes' : 'Jacarezinho'}` : 'Selecione um campus'
fixed

2023-03-29 12:14 UTC, Gabriellimmaa approved these changes

2023-03-29 12:14 UTC, merged